In [1]:
import cv2 as cv

In [9]:
#imread() reads the image in the given format and returns a 2D array if the image is not colored , if colored it returns a 3D array (R,G,B) just like below
filepath = 'C:\\Users\\sagitec\\Desktop\\Projects\\LearnITGirl\\SampleImages\\Sim&ria.jpeg'
original_image = cv.imread(filepath)
print(original_image)
original_image.ndim #ndim is n dimensions of array so it tells us if array is 2D or 3D

[[[ 88  52  58]
  [ 80  44  50]
  [ 84  48  54]
  ...
  [ 55  36  45]
  [ 55  36  45]
  [ 55  36  45]]

 [[ 87  51  57]
  [ 81  45  51]
  [ 86  50  56]
  ...
  [ 55  36  45]
  [ 55  36  45]
  [ 55  36  45]]

 [[ 86  50  56]
  [ 82  46  52]
  [ 89  53  59]
  ...
  [ 55  36  45]
  [ 55  36  45]
  [ 55  36  45]]

 ...

 [[ 78 100 111]
  [ 79 101 112]
  [ 72  94 105]
  ...
  [ 57  69  87]
  [ 57  69  87]
  [ 60  72  90]]

 [[ 85 107 118]
  [ 80 102 113]
  [ 67  89 100]
  ...
  [ 59  71  89]
  [ 58  70  88]
  [ 61  73  91]]

 [[ 91 113 124]
  [ 83 105 116]
  [ 69  91 102]
  ...
  [ 62  74  92]
  [ 61  73  91]
  [ 63  75  93]]]


3

In [8]:
#cvtColor() helps us change from one color spaces to another . Color spaces are BGR ,Gray
#cv.COLOR_BGR2GRAY is for BGR to Gray conversion that is why now a 2D array is stored in gray_image
#ndim(Number Of Array Dimensions) is a numpy ndarray attribute
gray_image = cv.cvtColor(original_image, cv.COLOR_BGR2GRAY)
gray_image.ndim

2

In [12]:
#haarcascade_frontalface_alt.xml is a pretrained classifier which is good for detecting frontal faces , it takes long time to train if dataset is large but gives better accuracy than other classifiers
#To use this classifier we need to use CascadeClassifier method which takes as parameter the filename where the classifier is loaded
path = ''C:\\Users\\sagitec\\Desktop\\Projects\\haarcascade_frontalface_alt.xml''
face_cascade = cv.CascadeClassifier(path)

In [16]:
"""
This detectMultiScale detects faces in the objects
Parameters of detectMultiScale are image , scaleFactor , minNeighbors , minSize , maxSize
image contains the matrix of the image which is put as input for detection
scaaleFactor : The model being used has a fixed size defined during training. This means that this size of face is detected in the image if it occurs. So by rescaling the input image, we can resize a larger face to a smaller one, making it detectable for the algorithm.
Using a small step for resizing, for example 1.05 which means we reduce size by 5 %, we increase the chance of a matching size with the model for detection is found
minNeighbors : Suppose there are 4 faces in the image and I set minNeighbors as 1 that means that if a rectangle has 1 or more neighbors it will be considered as a face . The higher this factor is set the lesser the detections will be but it will be more accurate
This is actually to rule out false positives.
minsize : Minimum possible object size that means that objects smaller than that are ignored.
maxsize : Maximum possible object size which means that objects larger than that are ignored.
"""
detected_faces = face_cascade.detectMultiScale(gray_image)
#Detected faces are returned as a list of rectangles
print(detected_faces)

[[102 376  21  21]
 [437 179 121 121]
 [576 209 124 124]
 [766 252  54  54]]


In [15]:
#cv2.rectangle(img, pt1, pt2, color, thickness, lineType, shift)
for (column, row, width, height) in detected_faces:
    cv.rectangle(
        original_image,
        (column, row),
        (column + width, row + height),
        (0, 255, 0),
        2
    )

In [17]:
#This function will display the image in a window and it receives as input the name of the window and the image we previously got with the imread function
cv.imshow('Image', original_image)

In [18]:
#waitkey(ms) the number represents for how many milliseconds is the image going to be displayed and 0 is a special case which means forever until a key is pressed
cv.waitKey(0)

-1

In [19]:
#closes any open window and de-allocates associated memory
cv.destroyAllWindows()